### ISSUE TITLE
Deploy KeyCloak service and register this service with the eduGAIN and Elixir AAI federations

### ISSUE THREAD

**Issue by cgizzi** [SixSq/hn-prototype-platform#1]
The prototype KeyCloak deployment by CYCLONE is not appropriate for a production infrastructure. The Consortium must deploy its own KeyCloak service and register this service with the eduGAIN and Elixir AAI federations. This work is largely administrative in nature, but is required before the platform can use the identity providers of these federations.

**Comment by cjdcordeiro** [comment]
we've setup a federated identity portal (fed-id) at https://fed-id.nuv.la/auth/
It used Keycloak and simpleSAMLphp to act as a Service Provider and authenticate through SWITCH and ELIXIR. User and technical documentation about this will be coming soon at https://github.com/SixSq/tasklist/issues/1117

The current state is:
 - We are registered with SWITCH, we can test some IdPs behind them and we are still waiting for the formal approval for becoming a interfederation Service Provider (I believe this will then also give us access to the full IdP list behind eduGAIN)
 - We are also registered (almost fully, just waiting for a formal appraisal) with ELIXIR AAI. We can already use their IdPs (we don't have credentials though so we've been testing with social providers there). 
 - onedata integration has already been tested with fed-id. Seems to work. Currently in the process of being validated and moved to production.
 - we currently integrating Nuvla with fed-id for a fully functional AAI workflow with our services.

I will close this ticket once the formal registration procedures with SWITCH and ELIXIR are fully finalized.

**Comment by cjdcordeiro** [comment]
SixSq Federated Identity Portal is now formally a SWITCH interfederation partner with access to SWITCHaai and eduGAIN IdPs.

Also, SixSq Federated Identity Portal is now formally registered with ELIXIR AAI. The privacy policy for this AAI can be found at http://sixsq.com/legal/aai_privacy and for further testing the AAI portal can be found at https://fed-id.nuv.la
