### ISSUE TITLE
Provide a formal response (by mail) to Buyers' questions on Onedata

### ISSUE THREAD

**Issue by cgizzi** [SixSq/hn-prototype-platform#14]
**Question 1:**
If (and when) OneProvider, to be installed @buyers site, could be installed on top of existing repositories (already containing file data). During the kick-off, I had the impression that OneProvider (still) requires a 'clean/empty' repository and all data have to be 'filled' through OneProvider. DESYs plan is to use a single (dedicated) instance of GPFS to be the base for  NFSv3 exports and OneProvider (at the same time). Did this work ?

**Question 2:**
How to make sure the file access authorization is replicated to the off-prem XXX instance through OneProvider. DESY used NFSv4 ACLs on all relevant systems. The ACLs contains (beside the standard UNIX mode bits) several entries referencing UNIX groups (not UIDs). The mapping of these groups to a set of IDs is maintained and exported through local LDAP. Thus, the usual management of ACLs is done by changing UIDs belonging to (UNIX) groups and no ACL needs to be changed once generated.

**Comment by cgizzi** [comment]
Please report to Lukasz

**Comment by mebster** [comment]
@bkryza please could we have an update on this?
