### ISSUE TITLE
delete readthedocs documentation

### ISSUE THREAD

**Issue by loomis** [SixSq/hn-prototype-platform#17]
As the repository containing the documentation is now private, it is no longer possible to use ReadTheDocs to host the rendered version. Remove the configuration from the ReadTheDocs service.

**Comment by loomis** [comment]
The HNSciCloud Rhea account is still active on ReadTheDocs, but the documentation for the project has been removed. The sources still exist in the GitHub repository, which is now under the SixSq organization.

**Comment by mebster** [comment]
If we want to use read the docs for public documentation, we could create a separate public repo

**Comment by mebster** [comment]
Created a new public repository (SixSq/hn-prototype-docs) and moved the documentation to it.  The doc is published here: http://hn-prototype-docs.readthedocs.io/en/latest/

**Comment by cgizzi** [comment]
@mebster has also the hook with hudson been also set?

**Comment by mebster** [comment]
@cgizzi hudson?

**Comment by cgizzi** [comment]
@mebster the hook that was set in the previous repository (named hudson*) I guess it is Jenkins, it was there for automated generation of the docs I understood.
