### ISSUE TITLE
Create cpu benchmarking component in SS

### ISSUE THREAD

**Issue by cjdcordeiro** [SixSq/hn-prototype-platform#22]

**Comment by cjdcordeiro** [comment]
This component uses ATLAS Kit Validation (KV) tool to perform the CPU benchmark.

Component: kv-benchmark
Application (which allows for terminating VMs automatically after the benchmark finishes): kv-benchmark-APP

Workspace in Nuvla: HNSciCloud-RHEA/Benchmarking

Description:
this benchmark expects some input parameters that are NOT essential for the execution of the benchmark. It will start a new VM and download the KV script from https://sdccloud.web.cern.ch/sdccloud/KV/IT-4143/index.html as referred in the HNSciCloud Technical Specifications. The following steps are then taken:
 - create and assign a fuse group to /dev/fuse (needed for mounting CVMFS)
 - run the KV
 - write the score to a runtime parameter, **kv_output**
 - push the KV log file into the deployment _REPORTS_ section
 - if *mail_to* was set, send the same log file by email
 - if the S3 credentials were set, it will put the compressed KV working directory (tarball automatically generated by the KV script) into S3

**Comment by tkotisis** [comment]
On Exoscale trying to run the app on a Small instance fails with the following output:

> Starting benchmark...!!!!!!!!!!!!!!!!!!!!!!!!! Running on el7 !!!!!!!!!!!!!!!!!!!!!!!!!KERNEL-RELEASE = 3.10.0-229.el7.x86_64WARNING: ratio between total MEMORY and number of CPUs is not satisfiedMEMORY = 489Number of CPUs = 1Stopping script
