### ISSUE TITLE
Issue with file replication between Oneproviders on S3

### ISSUE THREAD

**Issue by konstan** [SixSq/hn-prototype-platform#25]
We've setup one Onezone and two Oneprovider instances to test replication with S3.  
Both Oneproviders are pointing to OBS at OTC but use different buckets.
We used web UI on Oneprovider (id RjxqQ4.. see below) to upload a file and checked that the file is actually on OBS at OTC in the corresponding bucket.

Below is the attempt to replicate the file from provider RjxqQ4 to provider 9Aze5M via API.
We got transfer ID as the result of the request. The transfer is reported to be completed, but the file doesn't appear on provider 9Aze5M.  We tried this couple of times.  Same effect.

What are we doing wrong?

```
$ curl -k -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/replicas/s3-otc/clojure-cheatsheet.pdf | jq
[
  {
    "providerId": "RjxqQ4OVX_jdbKcLvySeHkmZLU64ZnDWURKo5qIQbOI",
    "blocks": [
      [
        0,
        69799
      ]
    ]
  }
]
$ curl -k -X POST -H "X-Auth-Token: $ACCESS_TOKEN"  "https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/replicas/s3-otc/clojure-cheatsheet.pdf?providerId=9Aze5MsQt1vvLQQbqV4iTNVGt_083t7pHes4woyYKdc" | jq
{
  "transferId": "g2dkACVvcF93b3JrZXJAbm9kZTEub25lcHJvdmlkZXIubG9jYWxob3N0AAAYXQAAAAEB"
}
$ curl -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/transfers -k | jq
[
  "g2dkACVvcF93b3JrZXJAbm9kZTEub25lcHJvdmlkZXIubG9jYWxob3N0AAAYXQAAAAEB",
  "g2dkACVvcF93b3JrZXJAbm9kZTEub25lcHJvdmlkZXIubG9jYWxob3N0AAAHMAAAAAEB",
  "g2dkACVvcF93b3JrZXJAbm9kZTEub25lcHJvdmlkZXIubG9jYWxob3N0AAB8tgAAAAAB"
]
$ curl -k -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/transfers/g2dkACVvcF93b3JrZXJAbm9kZTEub25lcHJvdmlkZXIubG9jYWxob3N0AAAYXQAAAAEB | jq
{
  "targetProviderId": "RjxqQ4OVX_jdbKcLvySeHkmZLU64ZnDWURKo5qIQbOI",
  "status": "completed",
  "path": "/s3-otc/clojure-cheatsheet.pdf"
}
$ curl -k -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/replicas/s3-otc/clojure-cheatsheet.pdf | jq
[
  {
    "providerId": "RjxqQ4OVX_jdbKcLvySeHkmZLU64ZnDWURKo5qIQbOI",
    "blocks": [
      [
        0,
        69799
      ]
    ]
  }
]
$
```

**Comment by konstan** [comment]
This documentation was used https://onedata.org/docs/doc/using_onedata/replication_management.html

**Comment by bkryza** [comment]
@konstan Could you please check if the 's3-otc' space is supported by both providers?

```
curl -k -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEZONE_HOST:8443/api/v3/onezone/user/spaces | jq '.'

{
  "spaces": [
    "<<SPACE_ID>>"
  ],
  "default": "undefined"
}

curl -k -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEZONE_HOST:8443/api/v3/onezone/user/spaces/<<SPACE_ID>> | jq '.'

{
   "providersSupports" : {
      ## HERE YOU SHOULD SEE BOTH PROVIDERS
   },
   "spaceId" : "<<SPACE_ID>>",
   "name" : "s3-otc"
}
```

If there's just one you need to add support to that space in the other provider's Onepanel interface...

**Comment by konstan** [comment]
Thanks.  Thant did the trick.  
However, the file wasn't physically replicated to S3 at Exoscale.  What I see is that only it's availability in another provider was declared.

![screen shot 2017-05-23 at 13 27 09](https://cloud.githubusercontent.com/assets/353767/26352436/0fcbb65c-3fbc-11e7-9755-2748a97a6ea5.png)
```
$ curl -k -X GET -H "X-Auth-Token: $ACCESS_TOKEN" https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/replicas/s3-otc/clojure-cheatsheet.pdf | jq
[
  {
    "providerId": "RjxqQ4OVX_jdbKcLvySeHkmZLU64ZnDWURKo5qIQbOI",
    "blocks": [
      [
        0,
        69799
      ]
    ]
  },
  {
    "providerId": "9Aze5MsQt1vvLQQbqV4iTNVGt_083t7pHes4woyYKdc",
    "blocks": []
  }
]
```
So, that when I switch to s3-exo, I don't see the file in the bucket.

![screen shot 2017-05-23 at 13 34 15](https://cloud.githubusercontent.com/assets/353767/26352550/8da3eb12-3fbc-11e7-932c-a8a6a2fc1cf7.png)

I suspect this is somehow related to the chunking we've discussed today in the call.  Please confirm.

At the same time, my initial replication -- when s3-otc wasn't supported by both providers -- should have failed and the transfer shouldn't have been reported "completed".  IMO, this is a bug.

**Comment by bkryza** [comment]
@konstan I will try to replicate this issue on some other setup, but this is definitely strange. Also, how did you manage to connect Exoscale S3 to Oneprovider without v2 signatures support?

**Comment by konstan** [comment]
No, none of Oneproviders was connected to Exoscale S3.  It was just one Oneprovider VM running on Exoscale, but it was connected to S3 at OTC.  So, there were two providers running: at Exoscale and OTC, and both of them connected to S3 at OTC, but they were using different buckets at OTC S3.

**Comment by konstan** [comment]
Hi @bkryza,  
Let me know if you need any extra info from us to reproduce the issue.

**Comment by bkryza** [comment]
@konstan 

```
$ curl -k -X POST -H "X-Auth-Token: $ACCESS_TOKEN"  "https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/replicas/s3-otc/clojure-cheatsheet.pdf?providerId=9Aze5MsQt1vvLQQbqV4iTNVGt_083t7pHes4woyYKdc" | jq
```

The argument is invalid - should be 'provider_id':

```
$ curl -k -X POST -H "X-Auth-Token: $ACCESS_TOKEN"  "https://$ONEPROVIDER_HOST:8443/api/v3/oneprovider/replicas/s3-otc/clojure-cheatsheet.pdf?provider_id=9Aze5MsQt1vvLQQbqV4iTNVGt_083t7pHes4woyYKdc" | jq
```

**Comment by bkryza** [comment]
@konstan
 
Yep, sorry I'll fix that, the REST API reference has this right:

https://onedata.org/#/home/documentation/doc/advanced/rest/oneprovider/operations/replicate_file.html

Also if you'll have issues, try to send the replication request also to the destination provider and see if this helps...

**Comment by loomis** [comment]
Via a discussion by Skype, the testing configuration of Konstantin is correct, but there is still an issue.  Lukasz suspects that this is an issue with token propagation that will be fixed in the v15 release expected today. 

This can be retested once the new release is available.

**Comment by konstan** [comment]
Validated with rc15.  Replication works. 
I'm closing this issue.
