### ISSUE TITLE
add SS component for Windows 2008 image

### ISSUE THREAD

**Issue by cjdcordeiro** [SixSq/hn-prototype-platform#32]

**Comment by elegoff** [comment]
after changing `Use native cloud contextualisation` from `linux-only` to `always`, the 2008 VM is deploying fine on OTC

**Comment by elegoff** [comment]
after updating its `image ID` , the win 2012 VM is deploying fine on OTC

**Comment by elegoff** [comment]
For Exoscale, the deployment fails until a newer version of Python (2.7.13) is installed. Connector code has to be updated to reflect this

**Comment by elegoff** [comment]
Win2008 and Win 2012 deployment tests are successful on : 
- OTC
- Exoscale GVA
- Exoscale DK
