### ISSUE TITLE
Exportation of binary images from BG clouds

### ISSUE THREAD

**Issue by cgizzi** [SixSq/hn-prototype-platform#36]
Define the procedure for exporting binary images from the Buyers Group to the platform’s cloud service providers.

**Comment by cjdcordeiro** [comment]
this is something that should be done directly with each cloud provider. The BG shall upload their images directly to each cloud individually

**Comment by cgizzi** [comment]
@loomis required interaction with BG for details on images. Mail to Monitoring newsletter or at the BG weekly meeting (Thursdays 12.00)

**Comment by loomis** [comment]
The ability to upload and use binary images from the BG organizations was a clear requirement in the tender.  Supporting this requires the ability for users/managers to upload new images to both Exoscale and OTC. 

@retrack Please provide documentation (or a reference to it) on the procedure that users/managers must follow to make their binary images available on Exoscale.

@eeckstei Please provide documentation (or a reference to it) on the procedure that users/managers  must follow to make their binary images available on OTC.

**Comment by retrack** [comment]
@loomis may I ask for the reference on the tender? 

We do not support this, it is too previous century ;-)

**Comment by eeckstei** [comment]
**Making private Images available on OTC via GUI:**
[Uploading an External Image File](https://docs.otc.t-systems.com/en-us/usermanual/ims/en-us_topic_0030713183.html)
[Registering the Image File as a Private Image](https://docs.otc.t-systems.com/en-us/usermanual/ims/en-us_topic_0030713184.html)
[Creating an ECS Using an Image](https://docs.otc.t-systems.com/en-us/usermanual/ims/en-us_topic_0030713200.html)
**Making private Images available on OTC via API:**
[Uploading an Image via API](https://docs.otc.t-systems.com/en-us/api/ims/en-us_topic_0031615566.html)
[Registering an Image File as a Private Image via API](https://docs.otc.t-systems.com/en-us/api/ims/en-us_topic_0037131984.html)

**Comment by loomis** [comment]
@retrack 
  * Section 3.2 of HNSciCloud FUNCTIONAL SPECIFICATION Phase 2. Asks for capabilities of custom images. 
  * Sections 8.1 and 8.2 of Buyers Group test plan refers to customized images. 
  * Criterium 13 of our Phase 2 proposal specifically mentions support for CernVM.

**Comment by mebster** [comment]
CernVM is one thing. Allowing any image upload is not something we should not support lightly. We can implement this requirement using our recipe based system and/or containers.

**Comment by loomis** [comment]
@mebster If the decision is "no binary images other than CernVM", I'm fine with that.  That's certainly much easier to implement.  Who will make the definitive decision on this?

**Comment by mebster** [comment]
For me the decision is already made.  The question is rather if we change that ;-)

**Comment by loomis** [comment]
Ok, closing ticket then as rejected.  @cgizzi please note this is the requirements analysis.

**Comment by mebster** [comment]
I think we'll have to nuance this a little.  The user requirement was initially upload of any user defined virtual machine image.  This is not the SlipStream model.  We prefer to promit interoperable recipe based deployments, based on existing and optimised base images.  Further, containers also allow to define 'binary image' which in some cases fulfils the intended requirement.  Finally, we can, on OTC, allow users to upload their customer images.  So I would not 'reject' the requirement, which would mean we are non-compliant.  Instead I would claim that we fulfil the requirement in a nuanced way.

**Comment by cgizzi** [comment]
think we have to anticipate to the BG what will be the our solution implemented. Even if 'old century' there might be situations in which one or more users will be blocked or will have to do a rework on their workloads when starting performing the tests. This is a topic for our weekly meetings with them, adding a bullet...

**Comment by cgizzi** [comment]
@mebster has provided an analysis that we can use as justification of the rquirement. We have explained our apporach to the BG (waiting for feedbacks). The issue can be closed.
