### ISSUE TITLE
Onezone shows "All your providers are offline" message despite at least one provider online

### ISSUE THREAD

**Issue by tkotisis** [SixSq/hn-prototype-platform#43]
The provider is running and it even shows up in Onezone as such (green icon in the list of providers).

However, the map is not visible and user is unable to open to Onedata page by clicking on the "Go to files" link.

![2017-06-09 11_36_14-onezone - all providers online issue](https://user-images.githubusercontent.com/909980/26970061-3a160800-4d08-11e7-8b7f-8b0a642b4569.png)

**Comment by tkotisis** [comment]
It seems that all providers have to be online for Onezone to display the map.

If true, shouldn't the message reflect this?

**Comment by groundnuty** [comment]
@tkotisis which docker image tag is it?

**Comment by tkotisis** [comment]
The image is "onedata/oneprovider:3.0.0-rc14".

**Comment by luman75** [comment]
@tkotisis that was fixed in rc15 it was minor GUI issue showing the message in wrong situation.

**Comment by groundnuty** [comment]
the `https://github.com/onedata/getting-started` repo was updated to rc15, please update. this bug was fixed in that versionn
