### ISSUE TITLE
integrate repository with sixsq planning board

### ISSUE THREAD

**Issue by loomis** [SixSq/hn-prototype-platform#8]
Add the repository to the SixSq planning board and add the necessary labels to track progress, projects, etc.

**Comment by loomis** [comment]
@cgizzi @tkotisis I need one of you to log into Waffle to create the necessary web hooks.  Go [here](https://waffle.io/slipstream/slipstream/join) and log in with your GitHub account.  You should see a red bar at the bottom with a "Create Hooks" button.  Hopefully, that will setup the hooks we need to integrate into our planning board.

**Comment by cgizzi** [comment]
I logged in at waffle.io, I have given waffle the authorization to access the github account, I see our issues on the board. I think it is done.

**Comment by loomis** [comment]
The repository has been moved to the SixSq organization.  The necessary labels have been created and the web hooks added to the transferred repository.
